fix: improve error handling in move-to-final-path job for module movement and Odoo service status check

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -60,29 +60,29 @@ move-to-final-path:
   environment:
     name: test
   script:
-  - ssh-keyscan -H "$ODOO_HOST" > known_hosts
-  - sshpass -p "$ODOO_PASSWORD" ssh -o UserKnownHostsFile=known_hosts "$ODOO_USER@$ODOO_HOST" "
-      if [ -d '$ODOO_DEST_PATH/temp/prueba_module' ]; then
-        echo '$ODOO_PASSWORD' | sudo -S mv '$ODOO_DEST_PATH/temp/prueba_module' '$ODOO_DEST_PATH/';
-        if [ \$? -eq 0 ]; then
-          echo 'Módulo movido con éxito a destino final';
-          echo '$ODOO_PASSWORD' | sudo -S rm -rf '$ODOO_DEST_PATH/temp/prueba_module';
-          echo 'Carpeta temp eliminada';
+    - ssh-keyscan -H "$ODOO_HOST" > known_hosts
+    - sshpass -p "$ODOO_PASSWORD" ssh -o UserKnownHostsFile=known_hosts "$ODOO_USER@$ODOO_HOST" "
+        if [ -d '$ODOO_DEST_PATH/temp/prueba_module' ]; then
+          echo '$ODOO_PASSWORD' | sudo -S mv '$ODOO_DEST_PATH/temp/prueba_module' '$ODOO_DEST_PATH/';
+          if [ \$? -eq 0 ]; then
+            echo 'Módulo movido con éxito a destino final';
+            echo '$ODOO_PASSWORD' | sudo -S rm -rf '$ODOO_DEST_PATH/temp';
+            echo 'Carpeta temp eliminada';
+          else
+            echo 'Error al mover el módulo';
+            exit 1;
+          fi
         else
-          echo 'Error al mover el módulo';
+          echo 'No se encontró el módulo en la carpeta temp';
           exit 1;
-        fi
-      else
-        echo 'No se encontró el módulo en la carpeta temp';
-        exit 1;
-      fi"
+        fi"
     - sshpass -p "$ODOO_PASSWORD" ssh -tt -o StrictHostKeyChecking=no "$ODOO_USER@$ODOO_HOST" "sudo -n /usr/bin/systemctl restart odoo"
     - sshpass -p "$ODOO_PASSWORD" ssh -tt -o StrictHostKeyChecking=no "$ODOO_USER@$ODOO_HOST" "
-      sudo -n /usr/bin/systemctl status odoo --no-pager;
-      if ! systemctl is-active --quiet odoo; then
-        echo 'Odoo NO está corriendo en producción';
-        exit 1;
-      fi"
+        sudo -n /usr/bin/systemctl status odoo --no-pager;
+        if ! systemctl is-active --quiet odoo; then
+          echo 'Odoo NO está corriendo en producción';
+          exit 1;
+        fi"
   rules:
     - if: '$CI_PIPELINE_SOURCE == "schedule"'
 
